### ISSUE TITLE
Fatal Error : call to a member function

### ISSUE THREAD

**Issue by rmdes** [mapkyca/KnownSitemap#1]
When I visit for the first time https://www.rmendes.net/sitemap.xml i get this fatal error : 

![screenshot_186](https://cloud.githubusercontent.com/assets/12155003/14941782/c4e3df6e-0fa8-11e6-93f7-cf67e0301406.png)

Fatal error: Call to a member function getObject() on boolean in /home/rmendes/rmendes.net/IdnoPlugins/Sitemap/Main.php on line 50
Oh no! Known experienced a problem!

Known experienced a problem with this page and couldn't continue. The technical details are as follows:

Fatal Error: /home/rmendes/rmendes.net/IdnoPlugins/Sitemap/Main.php:50 - "Call to a member function getObject() on boolean", on page www.rmendes.net/sitemap.xml
If you continue to have problems, open source users have a number of resources available: https://withknown.com/opensource

Also when I dig into the /rmendes.net root I don't see any sitemap.xml file created or robot.txt.

**Comment by rmdes** [comment]
This is still ongoing : https://www.rmendes.net/sitemap.xml

**Comment by rmdes** [comment]
Do i have something server side for the sitemap.xml to be generated ? 
I feel like I'm missing a requirement but none is listed on the readme.md

**Comment by herbsmn** [comment]
my site just says the generic Ruh Roh https://www.freekurt.com/sitemap.xml

I'm also curious if I need to do something server side, in nginx.

https://www.freekurt.com/robots.txt does pull up for me:

***

User-agent: *
Disallow:

Sitemap: https://freekurt.com/sitemap.xml

***

If this plugin isn't going to work, and I want to uninstall it, do I need to edit robot.txt back to something else?

Also, it looks like @mapkyca's site is pulling a similar error as yours is, @rikmendes : https://mapkyca.com/sitemap.xml

**Comment by mapkyca** [comment]
Hmm... sorry, I don't think I ever got a notification for this issue!

**Comment by herbsmn** [comment]
it works!!!

**Comment by herbsmn** [comment]
thanks @mapkyca!!!!
